server:
  port : 80
spring :
  jpa :
    show-sql : true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
  thymeleaf:
    cache: false
  freemarker:
    cache: false

dubbo:
  version: 1.0.0