server:
  port : 8060
spring :
  jpa :
    show-sql : true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
  thymeleaf:
    cache: false
  freemarker:
    cache: false

dubbo:
  version: 1.0.0

logging:
  level:
    org: info
    com: info

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com/demo/task/forkjoin/entity
